### ISSUE TITLE
厳格な静的型付けルールの導入: Pydantic と mypy を活用した型安全性の向上

### ISSUE THREAD

**Issue by NewAITees** [NewAITees/kokoro_mcp_server#12]
## 背景

高品質なコードベースを維持し、バグを早期に発見するために、より厳格な静的型付けルールを導入することを提案します。Python の動的型付け言語としての柔軟性を活かしつつ、静的型チェックの恩恵を得ることで、より安全で保守性の高いコードを実現します。

### mypy 設定の強化

`pyproject.toml` の mypy セクションを更新し、より厳格な型チェックを実施します:

```toml
[tool.mypy]
python_version = "3.10"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
strict_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
warn_unreachable = true

# サードパーティライブラリの型定義がない場合の設定
[[tool.mypy.overrides]]
module = ["some_untyped_module.*"]
ignore_missing_imports = true

# テストコードは型チェックを少し緩める
[[tool.mypy.overrides]]
module = "tests.*"
disallow_untyped_defs = false
disallow_incomplete_defs = false
```

### Pydantic の活用ルール

1. **データモデルの定義**:
   - すべてのデータモデルは `pydantic.BaseModel` を継承
   - すべてのフィールドに型アノテーションと `Field()` による制約・ドキュメントを追加
   - JSONからの変換が必要なデータには適切な validator/root_validator を実装

2. **型の厳格化**:
   - `Optional[Type]` と `Union[Type1, Type2]` の適切な使用
   - コレクション型にはジェネリクスを使用（`List[str]`, `Dict[str, Any]` など）
   - Pydantic の `StrictStr`, `PositiveInt` などの制約型の活用

### 型ヒントの一貫した使用

1. **関数とメソッド**:
   - すべての関数・メソッドのパラメータと戻り値に型ヒントを付ける
   - `Callable[[ArgType], ReturnType]` で関数型を明示
   - 非同期関数には `Awaitable[ReturnType]` を使用

2. **変数の型ヒント**:
   - クラス属性には常に型ヒントを付ける
   - 複雑な型の局所変数には型ヒントを付ける

3. **型の明示化**:
   - 型推論が難しい場合は明示的に型を注釈
   - キャストが必要な場合は `typing.cast()` を使用

### 型チェック自動化

1. **CI/CD パイプライン**:
   - GitHub Actions で mypy による型チェックを自動化
   - PRのマージ前に型チェックエラーがないことを確認

2. **開発サポート**:
   - VSCode や PyCharm などのエディタで mypy プラグインの使用を推奨
   - pre-commit フックに mypy チェックを追加

## 実装計画

1. 基本的な mypy 設定を `pyproject.toml` に追加（優先度: 高）
2. CI パイプラインに mypy チェックを追加（優先度: 高）
3. 主要なモデルと API 層に完全な型ヒントを追加（優先度: 高）
4. ユーティリティ関数と補助クラスに型ヒントを追加（優先度: 中）
5. テストコードにも基本的な型ヒントを追加（優先度: 低）

## 期待される効果

- バグの早期発見と修正
- コードの自己文書化と可読性の向上
- リファクタリングの安全性向上
- IDEによるコード補完と静的解析のサポート強化
- より堅牢なAPIの設計

## 注意点・検討事項

- 既存コードベースへの段階的適用（一度にすべてを変更するのではなく、モジュールごとに導入）
- サードパーティライブラリで型定義が不足している場合の対応
- 開発者へのトレーニングとガイドライン提供

## 参考リソース

- [mypy ドキュメント](https://mypy.readthedocs.io/)
- [Pydantic ドキュメント](https://docs.pydantic.dev/)
- [Python 型ヒントチートシート](https://mypy.readthedocs.io/en/stable/cheat_sheet_py3.html)
